FROM openjdk:8-jdk
COPY gradlew .
COPY gradle gradle
COPY build.gradle .
COPY settings.gradle .
COPY src src
RUN chmod +x ./gradlew
RUN ./gradlew bootJar
EXPOSE 8080
ENTRYPOINT ["./gradlew", "bootRun"]
